#!/usr/bin/env python

import ipaaca
import time

def iu_event_handler(iu, event_type, local):
	if event_type=='ADDED':
		iu.payload['receiver_local_t'] = time.time()
		print('Sent IPAACA ping reply')

ib = ipaaca.InputBuffer('IpaacaPong', ['ipaacaPing'])
ib.register_handler(iu_event_handler)

while True:
	time.sleep(1)

