#!/bin/bash
if [ -d /vol/soa/opt64/spread ]; then
	echo "Starting local-only spread daemon for ipaaca (from soa volume) ..."
	LD_LIBRARY_PATH=/vol/soa/opt64/spread/current/lib
	/vol/soa/opt64/spread/current/sbin/spread -n localhost &
else
	echo "Starting local-only spread daemon for ipaaca ..."
	spr=`which spread`
	[ $? -eq 0 ] || {
		echo spread not found in PATH - searching in /usr/sbin and /usr/local/sbin
		spr=''
		[ -e /usr/local/sbin/spread ] && spr="/usr/local/sbin/spread"
		[ -e /usr/sbin/spread ] && spr="/usr/sbin/spread"
		[ "$spr" = "" ] && echo "Could not find spread"
		echo $spr
	}
	${spr} -n localhost &
fi

